export const INIT_CART = 'app/CART/INIT_CART';
export const INIT_CART_SUCCESS = 'app/CART/INIT_CART_SUCCESS';
export const INIT_CART_ERROR = 'app/CART/INIT_CART_SUCCESS';

export const CHANGE_CART = 'app/CART/CHANGE_CART';
export const CHANGE_CART_SUCCESS = 'app/CART/CHANGE_CART_SUCCESS';
export const CHANGE_CART_ERROR = 'app/CART/CHANGE_CART_SUCCESS';

export const GET_CART = 'app/CART/GET_CART';
export const GET_CART_SUCCESS = 'app/CART/GET_CART_SUCCESS';
export const GET_CART_ERROR = 'app/CART/GET_CART_ERROR';

export const ADD_ITEM_CART = 'app/CART/ADD_ITEM_CART';
export const ADD_ITEM_CART_SUCCESS = 'app/CART/ADD_ITEM_CART_SUCCESS';
export const ADD_ITEM_CART_ERROR = 'app/CART/ADD_ITEM_CART_ERROR';

export const EDIT_ITEM_CART = 'app/CART/EDIT_ITEM_CART';
export const EDIT_ITEM_CART_SUCCESS = 'app/CART/EDIT_ITEM_CART_SUCCESS';
export const EDIT_ITEM_CART_ERROR = 'app/CART/EDIT_ITEM_CART_ERROR';

export const DELETE_ITEM_CART = 'app/CART/DELETE_ITEM_CART';
export const DELETE_ITEM_CART_SUCCESS = 'app/CART/DELETE_ITEM_CART_SUCCESS';
export const DELETE_ITEM_CART_ERROR = 'app/CART/DELETE_ITEM_CART_ERROR';

export const SHOW_CART = 'app/CART/SHOW_CART';
export const HIDDEN_CART = 'app/CART/HIDDEN_CART';

export const CLEAR_CART = 'app/CART/CLEAR_CART';
