export const LOAD_LIST_CATEGORY = 'app/CATEGORY/LOAD_LIST';
export const LOAD_LIST_CATEGORY_SUCCESS = 'app/CATEGORY/LOAD_LIST_SUCCESS';
export const LOAD_LIST_CATEGORY_ERROR = 'app/CATEGORY/LOAD_LIST_ERROR';

export const CREATE_CATEGORY = 'app/CATEGORY/CREATE';
export const CREATE_CATEGORY_SUCCESS = 'app/CATEGORY/CREATE_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'app/CATEGORY/CREATE_ERROR';

export const EDIT_CATEGORY = 'app/CATEGORY/EDIT';
export const EDIT_CATEGORY_SUCCESS = 'app/CATEGORY/EDIT_SUCCESS';
export const EDIT_CATEGORY_ERROR = 'app/CATEGORY/EDIT_ERROR';

export const DELETE_CATEGORY = 'app/CATEGORY/DELETE';
export const DELETE_CATEGORY_SUCCESS = 'app/CATEGORY/DELETE_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'app/CATEGORY/DELETE_ERROR';
