export const LOAD_LIST_PACKAGE = 'app/PACKAGE/LOAD_LIST';
export const LOAD_LIST_PACKAGE_SUCCESS = 'app/PACKAGE/LOAD_LIST_SUCCESS';
export const LOAD_LIST_PACKAGE_ERROR = 'app/PACKAGE/LOAD_LIST_ERROR';

export const CREATE_PACKAGE = 'app/PACKAGE/CREATE_PACKAGE';
export const CREATE_PACKAGE_SUCCESS = 'app/PACKAGE/CREATE_PACKAGE_SUCCESS';
export const CREATE_PACKAGE_ERROR = 'app/PACKAGE/CREATE_PACKAGE_ERROR';

export const CHECK_PACKAGE = 'app/PACKAGE/CHECK_PACKAGE';
export const CHECK_PACKAGE_SUCCESS = 'app/PACKAGE/CHECK_PACK_SUCCESS';
export const CHECK_PACKAGE_ERROR = 'app/PACKAGE/CHECK_PACK_ERROR';

export const ACCEPT_PACKAGE = 'app/PACKAGE/ACCEPT_PACKAGE';
export const ACCEPT_PACKAGE_SUCCESS = 'app/PACKAGE/ACCEPT_PACKAGE_SUCCESS';
export const ACCEPT_PACKAGE_ERROR = 'app/PACKAGE/ACCEPT_PACKAGE_ERROR';

export const DELETE_PACKAGE = 'app/PACKAGE/DELETE_PACKAGE';
export const DELETE_PACKAGE_SUCCESS = 'app/PACKAGE/DELETE_PACKAGE_SUCCESS';
export const DELETE_PACKAGE_ERROR = 'app/PACKAGE/DELETE_PACKAGE_ERROR';

export const GET_TURNOVER = 'app/PACKAGE/GET_TURNOVER';
export const GET_TURNOVER_SUCCESS = 'app/PACKAGE/GET_TURNOVER_SUCCESS';
export const GET_TURNOVER_ERROR = 'app/PACKAGE/GET_TURNOVER_ERROR';
