export const LOAD_LIST_PRODUCT = 'app/PRODUCT/LOAD_LIST';
export const LOAD_LIST_PRODUCT_SUCCESS = 'app/PRODUCT/LOAD_LIST_SUCCESS';
export const LOAD_LIST_PRODUCT_ERROR = 'app/PRODUCT/LOAD_LIST_ERROR';

export const LOAD_LIST_PRODUCT_HOME = 'app/PRODUCT/LOAD_LIST_HOME';
export const LOAD_LIST_PRODUCT_HOME_SUCCESS = 'app/PRODUCT/LOAD_LIST_HOME_SUCCESS';
export const LOAD_LIST_PRODUCT_HOME_ERROR = 'app/PRODUCT/LOAD_LIST_HOME_ERROR';

export const CREATE_PRODUCT = 'app/PRODUCT/CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'app/PRODUCT/CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'app/PRODUCT/CREATE_PRODUCT_ERROR';

export const EDIT_PRODUCT = 'app/PRODUCT/EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'app/PRODUCT/EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'app/PRODUCT/EDIT_PRODUCT_ERROR';

export const DELETE_PRODUCT = 'app/PRODUCT/DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'app/PRODUCT/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'app/PRODUCT/DELETE_PRODUCT_ERROR';

export const GET_ITEM_PRODUCT = 'app/PRODUCT/GET_ITEM_PRODUCT';
export const GET_ITEM_PRODUCT_SUCCESS = 'app/PRODUCT/GET_ITEM_PRODUCT_SUCCESS';
export const GET_ITEM_PRODUCT_ERROR = 'app/PRODUCT/GET_ITEM_PRODUCT_ERROR';
